---
output: 
  html_document:
    keep_md: true
---

<!-- automatically generated by rmarkdown::render()... don't edit this file go file the README.Rmd file -->

some stuff

[] task 1
[x] task 2
[] task 3

some other stuff and here is some math inline $a^2 + b^2 = c^2$.

and finally here is some math out of line:

```math
a^2 +
b^2 =
c^2
```

and now some more text to see where we are.
